import pandas as pd
import streamlit as st
from streamlit_pandas_profiling import st_profile_report
from ydata_profiling import ProfileReport

df = pd.read_csv("https://raw.githubusercontent.com/dataprofessor/data/master/iris.csv")
profile = ProfileReport(df,
                        title="Iris flower data set",
                        dataset={
                            "description": "This EDA report was generated by Pandas Profiling",
                            "copyright_holder": "Dagistan",
                            "copyright_year": "2023",
                            "url": "https://dagistankaradeniz.github.io/",
                        },
                        variables={
                            "descriptions": {
                                "Sepal.Length": "Sepal.Length independent variable",
                                "Sepal.Width": "Sepal.Width independent variable",
                                "Petal.Length": "Petal.Length independent variable",
                                "Petal.Width": "Petal.Width independent variable",
                                "Species": "Species. The label / dependent variable"
                            }
                        }
                        )
st.set_page_config(
   page_title="dk - Iris Dataset Pandas Profiling",
   layout="wide",
   initial_sidebar_state="expanded",
)
st.markdown("# Pandas Profiling in Streamlit!")
st.dataframe(df)
st.markdown("### `Python` Code to generate below report from above dataset...")
st.code("""
        import pandas as pd
        import streamlit as st
        from streamlit_pandas_profiling import st_profile_report
        from ydata_profiling import ProfileReport
        
        df = pd.read_csv("https://raw.githubusercontent.com/dataprofessor/data/master/iris.csv")

        st.dataframe(df)
        st_profile_report(profile)
        """)
st_profile_report(profile)
